/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;
import Controladores.ControladorEscritor;
import Dados.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author willi
 */
public final class JanelaInicial extends javax.swing.JFrame {
    
    private static JanelaInicial janelaInicial;
    private String arqProp = null;

    /**
     * Creates new form JanelaInicial
     */
    private JanelaInicial() {
        initComponents();
        inciaComImagens();
        chamaProperties();
        if (arqProp != null) {
            criaJanelas();
        }
    }
    public final void inciaComImagens () {
        ControladorEscritor menu = ControladorEscritor.getControladorEscritor();
        menu.alteraImagens ("marvelVSdc.jpg", lbImagem);
        menu.alteraImagens ("stanlee.png", lbImagem2);
        menu.alteraImagens ("jackkirby.jfif", lbImagem3);
    }

    public static JanelaInicial getJanelaIncioal () {
        if (janelaInicial == null) {
            janelaInicial = new JanelaInicial ();
        }
        return janelaInicial;
    }
    
    public final void chamaProperties () {
        int ask = JOptionPane.showConfirmDialog (null, 
                "Deseja abrir algum arquivo binário com informações?", 
                "Recuperar dados atráves de arquivo binario",
                JOptionPane.YES_NO_OPTION);
        if (ask == 0) {
            Properties propriedades = new Properties ();
            arqProp = propriedades.executa(propriedades);
        } else {
            JOptionPane.showMessageDialog(null, "OK! Seguir para janela inicial");
        }
    }
    
    public final void criaJanelas () {
        criaThread(JanelaEscritor.getJanelaEscritor(false, arqProp), false);
        criaThread(JanelaEditora.getJanelaEditora(arqProp), false);
        criaThread(JanelaQuadrinho.getJanelaQuadrinho(arqProp), false);
        criaThread(JanelaEscritor.getJanelaEscritor(true, arqProp), false);
    }
    
    public final static void criaThread (JFrame janela, boolean append) {
        java.awt.EventQueue.invokeLater(() -> {
            janela.setVisible(append);  
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();
        btEscritor = new javax.swing.JButton();
        btDesenhista = new javax.swing.JButton();
        btQuadrinhos = new javax.swing.JButton();
        btEditora = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbImagem2 = new javax.swing.JLabel();
        lbImagem3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        jLabel1.setText("Katholikós Kómiks");

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel2.setText("A sua Loja de Quadrinhos");

        lbImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btEscritor.setText("Escritores");
        btEscritor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscritorActionPerformed(evt);
            }
        });

        btDesenhista.setText("Desenhistas");
        btDesenhista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesenhistaActionPerformed(evt);
            }
        });

        btQuadrinhos.setText("Quadrinhos");
        btQuadrinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuadrinhosActionPerformed(evt);
            }
        });

        btEditora.setText("Editora");
        btEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditoraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel3.setText("Selecione a Aba em que deseja acessar:");

        lbImagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbImagem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(209, 209, 209))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btQuadrinhos)
                        .addGap(90, 90, 90)
                        .addComponent(btEditora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(btEscritor)
                        .addGap(73, 73, 73)
                        .addComponent(btDesenhista)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditora)
                    .addComponent(btQuadrinhos)
                    .addComponent(btEscritor)
                    .addComponent(btDesenhista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEscritorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscritorActionPerformed
        criaThread(JanelaEscritor.getJanelaEscritor(false, arqProp), true);
    }//GEN-LAST:event_btEscritorActionPerformed

    private void btEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditoraActionPerformed
        criaThread(JanelaEditora.getJanelaEditora(arqProp), true);
    }//GEN-LAST:event_btEditoraActionPerformed

    private void btQuadrinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuadrinhosActionPerformed
        criaThread(JanelaQuadrinho.getJanelaQuadrinho(arqProp), true);
    }//GEN-LAST:event_btQuadrinhosActionPerformed

    private void btDesenhistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesenhistaActionPerformed
        criaThread(JanelaEscritor.getJanelaEscritor(true, arqProp), true);
    }//GEN-LAST:event_btDesenhistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDesenhista;
    private javax.swing.JButton btEditora;
    private javax.swing.JButton btEscritor;
    private javax.swing.JButton btQuadrinhos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbImagem2;
    private javax.swing.JLabel lbImagem3;
    // End of variables declaration//GEN-END:variables
}
